config/routes.rb
Rails.application.routes.draw do
  extend Authenticator

  # authentification
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  resources :sessions, only: [ :show, :destroy ]
  resource :password, only: [ :edit, :update ]

  namespace :identity do
    resource :email, only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset, only: [ :new, :edit, :create, :update ]
  end

  namespace :user do
    resource :dashboard, only: [ :show ]
    resources :sessions, only: [ :index ]
  end

  authenticate :admin do
    mount SolidErrors::Engine, at: "/solid_errors"
  end

  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :user_agent, :ip_address

  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user

  before_create do
    self.user_agent = Current.user_agent
    self.ip_address = Current.ip_address
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  generates_token_for :email_verification, expires_in: 2.days do
    email
  end

  generates_token_for :password_reset, expires_in: 20.minutes do
    password_salt.last(10)
  end

  has_many :sessions, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 6 }

  normalizes :email, with: -> { _1.strip.downcase }

  before_validation if: :email_changed?, on: :update do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_request_details

  include Authentification

  def set_current_request_details
    Current.user_agent = request.user_agent
    Current.ip_address = request.ip
  end
end

app/controllers/concerns/authentification.rb
module Authentification
  extend ActiveSupport::Concern

  included do
    before_action :authenticate!

    helper_method :sign_in?

    def sign_in?
      authenticate.is_a?(Session)
    end

    private

    def authenticate!
      redirect_to sign_in_path unless sign_in?
    end

    def authenticate
      return unless cookies.signed[:session_token]
      return Current.session if Current.session

      Current.session = Session.find_by_id(cookies.signed[:session_token])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate!, only: [ :show ]
  def show
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_dashboard_path, notice: "Your password has been changed"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = Current.user
  end

  def user_params
    params.permit(:password, :password_confirmation, :password_challenge).with_defaults(password_challenge: "")
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  layout "authentification"

  skip_before_action :authenticate!

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session_record = @user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: session_record.id, httponly: true }

      send_email_verification
      redirect_to root_path, notice: "Welcome! You have signed up successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def send_email_verification
    UserMailer.with(user: @user).email_verification.deliver_later
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "authentification"

  before_action :redirect_if_signed_in, only: %i[new]

  skip_before_action :authenticate!, only: %i[new create]

  before_action :set_session, only: :destroy

  def new
  end

  def create
    user = User.authenticate_by(email: params[:email], password: params[:password])
    if user
      @session = user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: @session.id, httponly: true }

      redirect_to user_dashboard_path, notice: "Signed in successfully"
    else
      redirect_to sign_in_path(email_hint: params[:email]), alert: "That email or password is incorrect"
    end
  end

  def destroy
    @session.destroy
    redirect_back(fallback_location: user_sessions_path, notice: "That session has been logged out")
  end

  private

  def set_session
    @session = Current.user.sessions.find(params[:id])
  end

  def redirect_if_signed_in
    session = Session.find_by_id(cookies.signed[:session_token])
    redirect_to user_dashboard_path if session
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < ApplicationController
  def show
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < ApplicationController
  def index
    @sessions = Current.user.sessions.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/views/home/index.html.erb
<div class="hero min-h-[calc(100vh-4rem)]">
  <div class="hero-content text-center">
    <div class="max-w-md">
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<title><%= content_for(:title) || "Rails Craft" %></title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= yield :head %>

<link rel="manifest" href="/manifest.json">
<link rel="icon" href="/icon.png" type="image/png">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/icon.png">
<%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
<%= hotwire_livereload_tags if Rails.env.development? %>
<%= render "magic_test/support" if Rails.env.test? %>
<%= yield :head %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Album Catalog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/authentification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
    <%= render 'magic_test/support' if Rails.env.test? %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="min-h-[calc(100vh-4rem)] w-full flex flex-col items-center justify-center">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/shared/_authenticated.html.erb
<div class="navbar shadow">
  <div class="flex-1">
    <%= link_to "Rails Craft", user_dashboard_path, class: "btn btn-ghost text-xl" %>
  </div>

  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <li">
        <div class="dropdown dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar" id="navbar_toggle">
            <div class="w-10 rounded-full">
              <img
                alt="<%= Current.user.name %>"
                src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp" />
            </div>
          </div>  
          <ul
            tabindex="0"
            class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
            <li>
              <p class="">
                <%= Current.user.email %> <br />
                <%= t("navbar.greeting", name: Current.user.name) %>
              </p>
            </li>
            <li>
                <%= link_to t("navbar.sessions"), user_sessions_path %>
            </li>
              <li>
                <%= link_to t("navbar.password"), edit_password_path %>
              </li>
              <li>
                <%= button_to t("sign_out"), Current.session, method: :delete, id: :sign_out %>
            </li>
          </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class="toast">
  <%
  alerts = {
    info: "alert-info",
    notice: "alert-info",
    alert: "alert-warning",
    success: "alert-success",
    warning: "alert-warning",
    error: "alert-error"
  }
  icons = {
    info: "information-circle",
    notice: "information-circle",
    alert: "exclamation-triangle",
    success: "check-circle",
    warning: "exclamation-triangle",
    error: "x-circle"
  }
  %>
  <% flash.each_with_index do |(key, content), ind| %>
    <div class="alert <%= alerts[key.to_sym] %>">
        <%= heroicon icons[key.to_sym] || "information-circle", variant: :outline, options: {class: "h-8 w-8"} %>
        <%= content %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<% if sign_in? %>
  <%= render "shared/authenticated" %>
<% else %>
  <%= render "shared/unauthenticated" %>
<% end %>

app/views/shared/_unauthenticated.html.erb
<div class="navbar shadow px-4">
  <div class="justify-start">
    <%= link_to root_path, class: "btn btn-ghost" do %>
      Rails Craft
    <% end %>
  </div>
  <div class="flex-grow"></div>
  <div class="justify-end gap-4">
    <div class="flex gap-4 items-center">
      <%= link_to t("sign_up"), sign_up_path, class: "btn btn-primary btn-outline" %>
      <%= link_to t("login"), sign_in_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/user/dashboards/show.html.erb
<div class="container text-center mt-8">
</div>